import { GraphNodeHandler } from "../stateGraph/types.js";
import { safeRead, writeRunArtifact } from "./helpers.js";
import { NodeExecutionDeps } from "./types.js";
import { RunContextMemory } from "../memory/runContextMemory.js";
import { ConstraintProfile } from "../runConstraints.js";
import { resolveConstraintProfile } from "../constraintProfile.js";
import {
  ObjectiveMetricEvaluation,
  ObjectiveMetricProfile,
  resolveObjectiveMetricProfile
} from "../objectiveMetric.js";

export function createWritePaperNode(deps: NodeExecutionDeps): GraphNodeHandler {
  return {
    id: "write_paper",
    async execute({ run, graph }) {
      const runContextMemory = new RunContextMemory(run.memoryRefs.runContextPath);
      const constraintProfile = await resolveConstraintProfile({
        run,
        runContextMemory,
        llm: deps.llm,
        eventStream: deps.eventStream,
        node: "write_paper"
      });
      const objectiveMetricProfile = await resolveObjectiveMetricProfile({
        run,
        runContextMemory,
        llm: deps.llm,
        eventStream: deps.eventStream,
        node: "write_paper"
      });
      const objectiveEvaluation = await loadObjectiveEvaluation(runContextMemory, run.id);
      const tex = [
        "\\documentclass{article}",
        "\\usepackage{graphicx}",
        `\\title{${latexEscape(run.title)}}`,
        "\\begin{document}",
        "\\maketitle",
        "\\section{Research Context}",
        `Topic: ${latexEscape(run.topic)}.`,
        `Objective metric: ${latexEscape(run.objectiveMetric)}.`,
        "\\section{Writing Constraints}",
        ...renderConstraintLines(run.constraints, constraintProfile),
        "\\section{Introduction}",
        "This draft follows the configured research and writing constraints.",
        "\\section{Method}",
        "See experiment plan and implementation artifacts.",
        "\\section{Results}",
        ...renderResultsLines(run.objectiveMetric, objectiveMetricProfile, objectiveEvaluation),
        "\\section{Conclusion}",
        "This draft was generated by AutoResearch state graph runtime.",
        "\\bibliographystyle{plain}",
        "\\bibliography{references}",
        "\\end{document}"
      ].join("\n");

      const references = [
        "@article{autoref1,",
        "  title={AutoResearch generated reference},",
        "  author={AutoResearch},",
        "  year={2026}",
        "}"
      ].join("\n");

      const evidenceMap = JSON.stringify(
        {
          claims: [
            { claim_id: "c1", evidence_ids: ["ev_1"] },
            { claim_id: "c2", evidence_ids: ["ev_2"] }
          ]
        },
        null,
        2
      );

      await writeRunArtifact(run, "paper/main.tex", tex);
      await writeRunArtifact(run, "paper/references.bib", references);
      await writeRunArtifact(run, "paper/evidence_links.json", evidenceMap);

      deps.eventStream.emit({
        type: "NODE_COMPLETED",
        runId: run.id,
        node: "write_paper",
        payload: { artifacts: ["paper/main.tex", "paper/references.bib"] }
      });

      return {
        status: "success",
        summary: "Paper draft generated in LaTeX.",
        needsApproval: true,
        toolCallsUsed: 1
      };
    }
  };
}

function latexEscape(text: string): string {
  return text.replace(/[&_#%$]/g, " ").trim();
}

function renderConstraintLines(
  constraints: string[],
  profile: ConstraintProfile
): string[] {
  const lines: string[] = [];

  if (profile.writing.targetVenue) {
    lines.push(`Target venue: ${latexEscape(profile.writing.targetVenue)}.`);
  }
  if (profile.writing.toneHint) {
    lines.push(`Tone: ${latexEscape(profile.writing.toneHint)}.`);
  }
  if (profile.writing.lengthHint) {
    lines.push(`Length target: ${latexEscape(profile.writing.lengthHint)}.`);
  }
  if (profile.experiment.designNotes.length > 0) {
    lines.push("Design guidance:");
    for (const note of profile.experiment.designNotes) {
      lines.push(`- ${latexEscape(note)}`);
    }
  }
  if (profile.experiment.evaluationNotes.length > 0) {
    lines.push("Evaluation guidance:");
    for (const note of profile.experiment.evaluationNotes) {
      lines.push(`- ${latexEscape(note)}`);
    }
  }
  if (profile.assumptions.length > 0) {
    lines.push("Constraint assumptions:");
    for (const note of profile.assumptions) {
      lines.push(`- ${latexEscape(note)}`);
    }
  }

  if (constraints.length === 0) {
    lines.push("No additional run constraints were provided.");
    return lines;
  }

  lines.push("Run constraints:");
  for (const constraint of constraints) {
    lines.push(`- ${latexEscape(constraint)}`);
  }
  return lines;
}

async function loadObjectiveEvaluation(
  runContextMemory: RunContextMemory,
  runId: string
): Promise<ObjectiveMetricEvaluation | undefined> {
  const cached = await runContextMemory.get<ObjectiveMetricEvaluation>("objective_metric.last_evaluation");
  if (cached) {
    return cached;
  }
  try {
    const raw = await safeRead(`.autoresearch/runs/${runId}/objective_evaluation.json`);
    return raw ? (JSON.parse(raw) as ObjectiveMetricEvaluation) : undefined;
  } catch {
    return undefined;
  }
}

function renderResultsLines(
  objectiveMetric: string,
  objectiveMetricProfile: ObjectiveMetricProfile,
  objectiveEvaluation: ObjectiveMetricEvaluation | undefined
): string[] {
  const lines = [`Primary objective: ${latexEscape(objectiveMetric)}.`];

  if (objectiveEvaluation) {
    lines.push(`Objective evaluation: ${latexEscape(objectiveEvaluation.summary)}.`);
  } else if (objectiveMetricProfile.primaryMetric) {
    lines.push(`Primary metric of interest: ${latexEscape(objectiveMetricProfile.primaryMetric)}.`);
  }

  if (objectiveMetricProfile.paperEmphasis.length > 0) {
    lines.push("Result emphasis:");
    for (const note of objectiveMetricProfile.paperEmphasis) {
      lines.push(`- ${latexEscape(note)}`);
    }
  } else {
    lines.push("Metrics are linked with evidence IDs in metadata.");
  }

  return lines;
}
